### ISSUE TITLE
现在得MVC、MVP、MVVM框架分包都推荐用PBF么？

### ISSUE THREAD

**Issue by BroganGrow** [Blankj/AndroidStandardDevelop#10]
现在阿里巴巴内部的项目分包也是按功能分么？

**Comment by Blankj** [comment]
按功能那是肯定的，毋庸置疑

**Comment by BroganGrow** [comment]
包名多单词的话，规范是推荐用驼峰还是小写的加下划线？

**Comment by Blankj** [comment]
不要用驼峰，会有问题的。用全小写或者下划线分割。

**Comment by BroganGrow** [comment]
好的，刚刚看google的todoapp也是全小写的

**Comment by Blankj** [comment]
我就是用驼峰的，哈哈，可读性比较好，有问题可能是我搞错了，仁者见仁哈，比如 androidTest、compileDebugJavaWithJavac...

**Comment by BroganGrow** [comment]
下划线看起来格格不入；驼峰可读性好；全小写和整体风格统一，单可读性差；androidTest。。。看起来直接用驼峰得了，哈哈
